services:
  db:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diabetes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d diabetes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build: ./fastapi
    container_name: fastapi_container
    ports: 
      - "8000:8000"
    depends_on:
      - db
      - minio
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MINIO_ENDPOINT=http://minio:9000

  minio:
    image: minio/minio
    container_name: minio_container
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    container_name: mc_helper
    depends_on:
      - minio
    entrypoint:
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --ignore-existing myminio/raw-diabetes-data;
      /usr/bin/mc mb --ignore-existing myminio/mlflow;
      exit 0;
      "

  mlflow:
    build: ./mlflow
    container_name: mlflow_container
    command: mlflow server --backend-store-uri postgresql://user:password@db:5432/diabetes_db --default-artifact-root s3://mlflow/ --host 0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin

  jupyter:
    build: ./jupyterlab
    container_name: jupyter_container
    command: start-notebook.sh --NotebookApp.token='diabetes-jupyter'
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - MLFLOW_URL=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./reports:/home/jovyan/work/reports

  thingsboard:
    image: thingsboard/tb-postgres
    container_name: thingsboard_container
    ports:
      - "8080:9090"
    environment:
      TB_QUEUE_TYPE: in-memory
      TB_DB_TYPE: postgres
      TB_POSTGRES_HOST: db
      TB_POSTGRES_PORT: 5432
      TB_POSTGRES_DB: diabetes_db
      TB_POSTGRES_USERNAME: user
      TB_POSTGRES_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data: